### PR TITLE
Update pymolprobity.tar.gz

### PR DESCRIPTION
**Pull request by speleo3**
The tar.gz file was missing the latest fixes.

I suggest to remove that file at some point in the future. PyMOL's plugin manager should be able to install an archive snapshot from github. Unfortunately, previous versions fail because of the "tests" folder (PyMOL expects a single package, not two), that was fixed in https://github.com/schrodinger/pymol-open-source/commit/4252f8ab145b

The second commit is a cosmetic fix which suppresses a warning about spaces in object names.

### CODE REVIEW

**Comment by jaredsampson** [comment]
Thanks, Thomas. If I delete the .tar.gz in the future, what would be the best URL to use when installing via the plugin manager?

**Comment by speleo3** [comment]
Any of the archive links, e.g. master or a tagged version:
- https://github.com/jaredsampson/pymolprobity/archive/master.zip
- https://github.com/jaredsampson/pymolprobity/archive/v0.1.2.zip

Download, then use "Install from local file" in the plugin manager and browse for the zip file.

**Comment by rafaeltiveron** [comment]
Not working. "Unable to install plugin", message from Pymol. Which is the correct installation for Pymol 2.1.0?

**Comment by rafaeltiveron** [comment]
I deleted "test" folder and it installed. Thanks

**Pull request merged**
